name: Pull request

on:
  pull_request:

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8, 9, 10, 11, 12, 13, 14, 15, 16, 17]
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    - name: Use Node.js 17
      uses: actions/setup-node@v3
      with:
        node-version: 17
    - name: Install packages
      run: npm ci && npm run postinstall --if-present
    - name: Transpile with Typescript
      run: npm run dist --if-present
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Run tests
      run: npm run test --if-present
 